// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendMessage(arg1:string,arg2:string):Promise<string>;

export function SetConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function TestConnection():Promise<string>;
